### PR TITLE
Fixed the bug where descriptions wouldn't show up

### PR DESCRIPTION
**Pull request by souvorinkg**
Now, you get descriptions when you click a common plant ("Monstera deliciosa", "Quercus Alba", etc). To test, click on plant details until you see a description.

### CODE REVIEW

**Comment by souvorinkg** [comment]
Great, now you should see images with certain species, here's the norway oak, Aka Picea albies: 
image

**Comment by souvorinkg** [comment]
I added a commit where I changed the db so Taxa includes a PereID int column, this will save the ID I get from API calls so I only need it once.

**Comment by souvorinkg** [comment]
OK, now when you search up a known tree, you write the image URL and description in the DB. To test this feature, search up a tree like the bristlecone pine, it should be instantaneous. 

image

**Comment by souvorinkg** [comment]
OK, now the description and urls are added to the DB as well, so you don't need to make repeat calls for them.

**Comment by HaydenMoussa** [comment]
Looks good. Was having some trouble with finding the proper plants, but I think that has more to do with the search logic than what you are implementing here.

**Pull request merged**
